spring.application.name=internship-management-system

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/internship-management-system
spring.datasource.username=rikkei
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
